import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from './NavBar';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <Navbar />
          <main className="flex-1 p-4">{children}</main> {/* Page content */}
        </Theme>
      </body>
    </html>
  );
}
