import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalStyleProvider from './providers/GlobalStyleProvider'
import Sidebar from './components/sidebar/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyleProvider>
          <Sidebar />
          {children}
        </GlobalStyleProvider>
        </body>  
    </html>
  )
}
